name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DB_NAME: test
      DB_HOST: localhost
      DB_USER: test
      DB_PASSWORD: test
      DB_PORT: 3316
      JWT_SECRET: test
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
#     - name: Unit Tests
#       run: npm run test:cov
#     - name: Codecov
#       uses: codecov/codecov-action@v1.2.2
#       with:
#         directory: ./coverage
    - run: docker-compose up -d
    - name: E2E Tests
      run: npm test
    - name: build
      run: npm run build      
