name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      DB_NAME: test
      DB_HOST: localhost
      DB_USER: test
      DB_PASSWORD: test
      DB_PORT: 3316
      GOOGLE_CLIENT_ID: test
      GOOGLE_CLIENT_SECRET: test
      GOOGLE_CALLBACK_URL: test
      JWT_SECRET: test
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - name: Unit Tests
      run: npm run test:cov
    - name: Report to Codecov
      uses: codecov/codecov-action@v1.2.2
      with:
        directory: ./coverage
    - run: docker-compose -f docker-compose-test-mysql.yaml up -d
    - name: E2E Tests
      run: npm test
